In [6]:
import numpy as np
import matplotlib.pyplot as plt
import math
import pandas as pd

In [2]:
def rk4_vector(F, a, b, x0, n):
    """
    x0 = [t0, x, y] init value (x(t0), y(t0))
    """
    u = np.zeros((n + 1, len(x0)))
    u[0] = np.copy(x0)
    h = (b - a)/n
    for i in range(n):
        K1 = F(u[i])
        K2 = F(u[i] + 1/2*h*K1)
        K3 = F(u[i] + 1/2*h*K2)
        K4 = F(u[i] + h*K3)
        # Runge Kutta's method
        u[i + 1] = u[i] + 1/6*h*(K1 + 2*K2 + 2*K3 + K4)
    return u

def linear(y0, y1, z0, z1, beta):
    """
    z0, z1 any values
    y0, y1 boundary of z1 and z2 respectively 
    beta: boundary condition
    """
    return z0 + (beta - y0)/(y1 - y0)*(z1 - z0)

def secant_method(y0, y1, z0, z1, beta):
    """
    z1, z2 any values
    y1, y2 boundary of z1 and z2 respectively 
    beta: boundary condition
    """
    return z1 - (y1 - beta)/(y1 - y0)*(z1 - z0)

### Método del disparo lineal
#### Session 17 page 12 (Observation: If it matches) 

In [7]:
def F(u):
    dx = 1
    dT = u[2]
    dz = 0.01*(u[1] - 20)
    return np.array([dx, dT, dz])

# valores iniciales T(a)=alpha, T(b)=beta
a = 0   
b = 10
alpha = 40
beta = 200
n = 2
np.set_printoptions(precision=11)

z1 = 10 # considerando como valor inicial  
u0 = [a, alpha, z1]
print(f"Runge Kutta O4, para z(0)={z1}")
u1 = rk4_vector(F, a, b, u0, n)
print(u1)

z2 = 20 # considerando como valor inicial  
u0 = [a, alpha, z2]
print(f"Runge Kutta O4, para z(0)={z2}")
u2 = rk4_vector(F, a, b, u0, n)
print(u2)

# z(0) =  interpolando z1(0) y z2(0)
z = linear(u1[n, 1], u2[n, 1], z1, z2, beta)
u0 = [a, alpha, z]
print(f"Runge Kutta O4, para z(0)={z}")
print(rk4_vector(F, a, b, u0, n))

Runge Kutta O4, para z(0)=10
[[  0.             40.             10.           ]
 [  5.             94.63541666667  12.31770833333]
 [ 10.            168.31393771701  17.77676052517]]
Runge Kutta O4, para z(0)=20
[[  0.             40.             20.           ]
 [  5.            146.71875        23.59375      ]
 [ 10.            285.77270507812  33.20434570312]]
Runge Kutta O4, para z(0)=12.697632794457277
[[  0.             40.             12.69763279446]
 [  5.            108.68558747113  15.3595703125 ]
 [ 10.            200.             21.93855649671]]


### Método del disparo no lineal
#### Session 17 page 23 (Obs: El final no coincide, preguntar)

In [8]:
def F(u):
    dx = 1
    dT = u[2]
    dz = 5e-8*(u[1] - 20)**4
    return np.array([dx, dT, dz])

# valores iniciales T(a)=alpha, T(b)=beta
a = 0   
b = 10
alpha = 40
beta = 200
n = 2
np.set_printoptions(precision=11, suppress=True)

z1 = 12 # considerando como valor inicial  
u0 = [a, alpha, z1]
print(f"Runge Kutta O4, para z(0)={z1}")
u1 = rk4_vector(F, a, b, u0, n)
print(u1)

z2 = 10 # considerando como valor inicial  
u0 = [a, alpha, z2]
print(f"Runge Kutta O4, para z(0)={z2}")
u2 = rk4_vector(F, a, b, u0, n)
print(u2)

for k in range(5):
    # z(0) =  interpolando z1(0) y z2(0)
    z = secant_method(u1[n, 1], u2[n, 1], z1, z2, beta)
    u0 = [a, alpha, z]
    print(f"Runge Kutta O4, para z(0)={z}")
    u1 = u2
    u2 = rk4_vector(F, a, b, u0, n)
    print(u2)
    z1 = u1[0, 2]
    z2 = u2[0, 2]

Runge Kutta O4, para z(0)=12
[[  0.             40.             12.           ]
 [  5.            102.64271615104  15.11563828612]
 [ 10.            300.98021475386 355.7441433433 ]]
Runge Kutta O4, para z(0)=10
[[  0.             40.             10.           ]
 [  5.             91.74573029115  11.8467985264 ]
 [ 10.            208.59995235885  96.49163787705]]
Runge Kutta O4, para z(0)=9.813814073788166
[[  0.             40.              9.81381407379]
 [  5.             90.7450807393   11.56819378037]
 [ 10.            202.1758767752   86.55196238952]]
Runge Kutta O4, para z(0)=9.750751672445357
[[  0.             40.              9.75075167245]
 [  5.             90.40664403362  11.47469423895]
 [ 10.            200.06409540578  83.46331897949]]
Runge Kutta O4, para z(0)=9.748837643719598
[[  0.             40.              9.74883764372]
 [  5.             90.3963758642   11.47186314952]
 [ 10.            200.00049304291  83.37163547578]]
Runge Kutta O4, para z(0)=9.748822806247

### PVF-disparo-dfinitas pagina 3

In [10]:
def F(u):
    dx = 1
    dy = u[2]
    dz = -2*u[2] - u[1]
    return np.array([dx, dy, dz])

# valores iniciales T(a)=alpha, T(b)=beta
a = 0   
b = 1
alpha = 1
beta = 3
n = 10
np.set_printoptions(precision=11, suppress=True)

z1 = 5 # considerando como valor inicial  
u0 = [a, alpha, z1]
print(f"Runge Kutta O4, para z(0)={z1}")
u1 = rk4_vector(F, a, b, u0, n)
print(u1)

z2 = 10 # considerando como valor inicial  
u0 = [a, alpha, z2]
print(f"Runge Kutta O4, para z(0)={z2}")
u2 = rk4_vector(F, a, b, u0, n)
print(u2)

for k in range(1):
    # z(0) =  interpolando z1(0) y z2(0)
    z = secant_method(u1[n, 1], u2[n, 1], z1, z2, beta)
    u0 = [a, alpha, z]
    print(f"Runge Kutta O4, para z(0)={z}")
    u1 = u2
    u2 = rk4_vector(F, a, b, u0, n)
    print(u2)
    z1 = u1[0, 2]
    z2 = u2[0, 2]

Runge Kutta O4, para z(0)=5
[[ 0.             1.             5.           ]
 [ 0.1            1.4477375      3.9812875    ]
 [ 0.2            1.80120345891  3.11118194953]
 [ 0.3            2.07428544112  2.37062509089]
 [ 0.4            2.27908157414  1.74284015937]
 [ 0.5            2.42611535869  1.21307024785]
 [ 0.6            2.52452580017  0.76834580609]
 [ 0.7            2.58223561288  0.39727809915]
 [ 0.8            2.60609994875  0.08987578966]
 [ 0.9            2.60203783377 -0.16261788657]
 [ 1.             2.57514825664 -0.36786961016]]
Runge Kutta O4, para z(0)=10
[[ 0.             1.            10.           ]
 [ 0.1            1.90015416667  8.05305833333]
 [ 0.2            2.61993059016  6.38610932531]
 [ 0.3            3.18550795706  4.96349468496]
 [ 0.4            3.61971597848  3.75380719961]
 [ 0.5            3.94243571225  2.72940456641]
 [ 0.6            4.17095402166  1.86597725648]
 [ 0.7            4.32027727472  1.14216453066]
 [ 0.8            4.4034088312